### ISSUE TITLE
SEGMENT VIOLATION on user /part

### ISSUE THREAD

**Issue by BigBadWouf** [eggheads/eggdrop#1708]
Hello 

i run an eggdrop v1.10.0 on Linux 6.1.106-1-MANJARO with python module. (tested without python module)
Eggdrop crash when user /part just after bot join channel, with or without script loaded.

Tested without script and with only vital module. 

Edit1: It seem happen only during join phase of the bot... If no /part during something like one minute, the /part not produce crash... 

``[18:57:13] * Last bind (may not be related): evnt:init_server``
``[18:57:12] * Wrote DEBUG``
``[18:57:12] * SEGMENT VIOLATION -- CRASHING!``

``[18:57:12] * eggdrop(lamest@fooBar) vient de rentrer``
``[18:57:13] * RandomUser (foo@Bar) est parti``
``[18:57:13] * eggdrop a quitté (Connection closed)``

Reproduce : 
Just compile an eggdrop 1.10.0, 
comment the two die line in config, 
add a serveur, 
add some channels, 
launch, 
make user /part just after bot join, 
crash...

[DEBUG.log](https://github.com/user-attachments/files/17510353/DEBUG.log)

Edit: After a few tests, random /part can produce crash

**Comment by michaelortmann** [comment]
Thank you for reporting.

Looks like an "account tracking" regression.

When `ismember()` can return `0` and`get_user_from_member()` cannot be called with `0` then code using of those functions must account for not passing `0` around.

Alternatively one of those functions must avoid / handle 0. Could be an issue with with our new "user lookup cache"?

There are more places than `gotpart()` who look similarly fragile.

```
.+chan #test666
[22:59:21] tcl: builtin dcc call: *dcc:+chan -HQ 1 #test666
[22:59:21] [!s] JOIN #test666
[22:59:21] #-HQ# +chan #test666
[22:59:22] [s->] JOIN #test666
[22:59:22] [@] :BotA!~BotA@localhost JOIN #test666 * :A deranged product of evil coders
[22:59:22] BotA joined #test666.
[22:59:22] [!m] MODE #test666 +b
[22:59:22] [m->] MODE #test666 +b
[22:59:22] [!m] MODE #test666 +e
[22:59:22] [m->] MODE #test666 +e
[22:59:22] [!m] MODE #test666 +I
[22:59:22] [m->] MODE #test666 +I
[22:59:22] [!m] MODE #test666
[22:59:22] [!m] WHO #test666 c%chnufat,222
[22:59:22] [@] :zen.home.arpa 353 BotA = #test666 :BotA @michael
[22:59:22] [@] :zen.home.arpa 366 BotA #test666 :End of /NAMES list.
[22:59:22] [@] :zen.home.arpa 368 BotA #test666 :End of Channel Ban List
[22:59:22] [@] :zen.home.arpa 482 BotA #test666 :You're not a channel operator
[22:59:22] [@] :zen.home.arpa 482 BotA #test666 :You're not a channel operator
[22:59:23] [@] :michael!~michael@localhost PART #test666
userrec.c:247:8: runtime error: member access within null pointer of type 'struct memberlist'
[22:59:23] * Please report problem to https://github.com/eggheads/eggdrop/issues
[22:59:23] * Check doc/BUG-REPORT on how to do so.
[22:59:23] * Last bind (may not be related): evnt:init_server
[22:59:22] * Wrote DEBUG
[22:59:22] * SEGMENT VIOLATION -- CRASHING!
Segmentation fault (core dumped)
```

```
(gdb) bt full
#0  0x000063f8a6806669 in get_user_from_member (m=0x0) at userrec.c:247
        ret = 0x0
#1  0x00007b6011b5cf14 in gotpart (from=0x5290000b9798 "~michael@localhost", msg=0x52900006ecb8 "")
    at .././irc.mod/chan.c:2260
        nick = 0x5290000b9790 "michael"
        chname = 0x52900006ecb0 "#test666"
        key = 0x5290000b5f70 "*raw:irc:part"
        chan = 0x51f000000e80
        u = 0x52900000f210
        m = 0x0
#2  0x00007b6011f1325b in server_raw (cd=0x7b6011b5c5ed <gotpart>, irp=0x52900000f210, argc=4, argv=0x504000010dd0)
    at .././server.mod/server.c:1410
        F = 0x7b6011b5c5ed <gotpart>
#3  0x000063f8a679d3d6 in tcl_call_stringproc_cd (cd=0x50200000a3f0, interp=0x52900000f210, objc=4, objv=0x5290000144f0)
    at tcl.c:332
        max = 0
        argv = 0x504000010dd0
        i = 4
        info = 0x50200000a3f0
#4  0x00007b6016c7e800 in TclNRRunCallbacks (interp=interp@entry=0x52900000f210, result=0, rootPtr=0x0)
    at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:4539
        callbackPtr = 0x52d000015270
        procPtr = <optimized out>
        iPtr = 0x52900000f210
#5  0x00007b6016c7e885 in Tcl_EvalObjv (interp=interp@entry=0x52900000f210, objc=objc@entry=4, 
    objv=objv@entry=0x5290000144f0, flags=flags@entry=2097168) at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:4262
        result = <optimized out>
        rootPtr = <optimized out>
#6  0x00007b6016c807e5 in TclEvalEx (interp=interp@entry=0x52900000f210, 
    script=0x7fff129c3f50 "*raw:irc:part $_raw1 $_raw2 $_raw3", numBytes=<optimized out>, numBytes@entry=-1, 
    flags=flags@entry=0, line=line@entry=1, clNextOuter=clNextOuter@entry=0x0, 
    outerScript=0x7fff129c3f50 "*raw:irc:part $_raw1 $_raw2 $_raw3") at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:5408
        wordLine = <optimized out>
        wordCLNext = <optimized out>
        objectsNeeded = <optimized out>
        wordStart = <optimized out>
        numWords = <optimized out>
        iPtr = <optimized out>
        p = 0x7fff129c3f50 "*raw:irc:part $_raw1 $_raw2 $_raw3"
        next = <optimized out>
        minObjs = <optimized out>
        objv = <optimized out>
        objvSpace = 0x5290000144f0
        expand = 0x5290000145a0
        lines = 0x529000014600
        lineSpace = 0x529000014600
        tokenPtr = <optimized out>
        commandLength = <optimized out>
        bytesLeft = 34
        expandRequested = <optimized out>
        code = <optimized out>
        savedVarFramePtr = 0x52900000d610
        allowExceptions = 0
        gotParse = 1
        i = <optimized out>
        objectsUsed = 4
        parsePtr = 0x529000014240
        eeFramePtr = 0x529000014490
        stackObjArray = 0x5290000144f0
        expandStack = 0x5290000145a0
        linesStack = 0x529000014600
        clNext = <optimized out>
#7  0x00007b6016c81097 in Tcl_EvalEx (interp=interp@entry=0x52900000f210, script=<optimized out>, numBytes=numBytes@entry=-1, 
    flags=flags@entry=0) at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:5073
#8  0x00007b6016c810ba in Tcl_Eval (interp=interp@entry=0x52900000f210, script=<optimized out>)
    at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:6001
        code = <optimized out>
#9  0x00007b6016c816e0 in Tcl_VarEvalVA (interp=0x52900000f210, argList=argList@entry=0x7fff129c4040)
    at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:7001
        buf = {string = 0x7fff129c3f50 "*raw:irc:part $_raw1 $_raw2 $_raw3", length = 34, spaceAvl = 200, 
          staticSpace = "*raw:irc:part $_raw1 $_raw2 $_raw3\000wt3 $_rawt4\000\000@\321\001\000 P\000\000\000T\373\336\345vu\243P\321\001\000 P\000\000@O\001\000\320R\000\000\001", '\000' <repeats 15 times>, "\200n\337\026`{\000\000\200@\234\022\377\177\000\000\020\362\000\000\220R\000\000l\323\327\026`{\000\000\001\000\000\000\377\177\000\000\000\000\000\000\000\000\000\000\327\320\332\026`{\000\000\355\322\326\026`{\000\000\220\257\f\000\220R\000\000\300\270\327\026`{\000\000`@\234\022\377\177", '\000' <repeats 17 times>}
        string = 0x7fff129c3960 "\300;\234\022\377\177"
        result = <optimized out>
#10 0x00007b6016c817be in Tcl_VarEval (interp=<optimized out>) at /usr/src/debug/tcl/tcl8.6.14/generic/tclBasic.c:7032
        argList = {{gp_offset = 32, fp_offset = 48, overflow_arg_area = 0x7fff129c4120, reg_save_area = 0x7fff129c4060}}
        result = <optimized out>
#11 0x000063f8a67c7b69 in trigger_bind (proc=0x50200000a430 "*raw:irc:part", param=0x7b6011f29c40 " $_raw1 $_raw2 $_raw3", 
    mask=0x50200000a410 "PART") at tclhash.c:745
        x = 32767
        ru1 = {ru_utime = {tv_sec = 0, tv_usec = 0}, ru_stime = {tv_sec = 0, tv_usec = 0}, {ru_maxrss = 0, 
            __ru_maxrss_word = 0}, {ru_ixrss = 0, __ru_ixrss_word = 0}, {ru_idrss = 0, __ru_idrss_word = 0}, {ru_isrss = 0, 
            __ru_isrss_word = 0}, {ru_minflt = 0, __ru_minflt_word = 0}, {ru_majflt = 0, __ru_majflt_word = 0}, {
            ru_nswap = 0, __ru_nswap_word = 0}, {ru_inblock = 0, __ru_inblock_word = 0}, {ru_oublock = 0, 
            __ru_oublock_word = 0}, {ru_msgsnd = 0, __ru_msgsnd_word = 0}, {ru_msgrcv = 0, __ru_msgrcv_word = 0}, {
            ru_nsignals = 0, __ru_nsignals_word = 0}, {ru_nvcsw = 0, __ru_nvcsw_word = 0}, {ru_nivcsw = 0, 
            __ru_nivcsw_word = 0}}
        ru2 = {ru_utime = {tv_sec = 0, tv_usec = 0}, ru_stime = {tv_sec = 0, tv_usec = 0}, {ru_maxrss = 0, 
            __ru_maxrss_word = 0}, {ru_ixrss = 0, __ru_ixrss_word = 0}, {ru_idrss = 0, __ru_idrss_word = 0}, {ru_isrss = 0, 
            __ru_isrss_word = 0}, {ru_minflt = 0, __ru_minflt_word = 0}, {ru_majflt = 0, __ru_majflt_word = 0}, {
            ru_nswap = 0, __ru_nswap_word = 0}, {ru_inblock = 0, __ru_inblock_word = 0}, {ru_oublock = 0, 
            __ru_oublock_word = 0}, {ru_msgsnd = 0, __ru_msgsnd_word = 0}, {ru_msgrcv = 0, __ru_msgrcv_word = 0}, {
            ru_nsignals = 0, __ru_nsignals_word = 0}, {ru_nvcsw = 0, __ru_nvcsw_word = 0}, {ru_nivcsw = 0, 
            __ru_nivcsw_word = 0}}
        r = 0
#12 0x000063f8a67c8b97 in check_tcl_bind (tl=0x504000002050, match=0x7b6013d5918c "PART", atr=0x0, 
    param=0x7b6011f29c40 " $_raw1 $_raw2 $_raw3", match_type=162) at tclhash.c:879
        x = 61968
        result = 0
        cnt = 1
        finish = 0
        proc = 0x0
        mask = 0x0
        tm = 0x50300000b050
        tm_last = 0x50300000b080
        tm_p = 0x50300000b080
        tc = 0x506000005f60
        htc = 0x0
        str = 0x52100002bd00 "\004"
        varName = 0x0
        brkt = 0x0
#13 0x00007b6011ecfcde in check_tcl_raw (from=0x7b6013d59171 "michael!~michael@localhost", code=0x7b6013d5918c "PART", 
    msg=0x7b6013d59191 "#test666") at .././server.mod/servmsg.c:202
        x = 3
#14 0x00007b6011ee3852 in server_activity (idx=4, tagmsg=0x7b6013d59170 ":michael!~michael@localhost", len=41)
    at .././server.mod/servmsg.c:1269
        from = 0x7b6013d59171 "michael!~michael@localhost"
        code = 0x7b6013d5918c "PART"
        msgptr = 0x7b6013d59191 "#test666"
        rawmsg = "\000michael!~michael@localhost PART #test666\000EFIX=(ov)@+ MAXLIST=bqeI:100 MODES=4 NETWORK=StaticBox STATUSMSG=@+ CASEMAPPING=rfc1459 NICKLEN=30 MAXNICKLEN=31 CHANNELLEN=50 TOPICLEN=390 DEAF=D :are suppor"...
        ret = 0
        tagdict = 0x52d000015150
#15 0x000063f8a675baed in mainloop (toplevel=1) at ./main.c:787
        idx = 4
        cleanup = 5
        xx = 8
        i = 41
        eggbusy = 1
        buf = ":michael!~michael@localhost\000PART\000#test666\000st * :A deranged product of evil coders", '\000' <repeats 16304 times>
#16 0x000063f8a675fe56 in main (arg_c=3, arg_v=0x7fff129cafa8) at ./main.c:1213
        i = 0
        j = 22
        xx = 18616
        s = <error reading variable s (Cannot access memory at address 0x671c0632)>
        f = 0x0
        sv = <error reading variable sv (Cannot access memory at address 0x671c0552)>
        chan = 0x0
        cdlim = <error reading variable cdlim (Cannot access memory at address 0x671c0532)>
```
